"""empty message

Revision ID: f377fff54870
Revises: b461795a6389
Create Date: 2021-09-07 18:03:27.138158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f377fff54870'
down_revision = 'b461795a6389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
