"""empty message

Revision ID: f3f5aca9a571
Revises: f377fff54870
Create Date: 2021-09-07 18:46:36.924729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f5aca9a571'
down_revision = 'f377fff54870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
